name: Build

on:
  workflow_dispatch:
  pull_request:
    branches: [ vnext, release ]
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - '**/*.config'
      - '**/*.ini'
      - '**/*.fbx'
      - '**/*.nca'
      - '**/*.png'
      - '**/*.jpg'
      - '**/*.jpeg'

jobs:
  Build:
    strategy:
      matrix:
        include:
          - name: "Win-VS"
            os: windows-2022
            generator: "Visual Studio 17 2022"
            definitions: "-DNC_COMMON_STATIC_ANALYSIS=ON"
          - name: "Win-MinGW"
            os: windows-2022
            generator: "Ninja"
            definitions: "-DCMAKE_BUILD_TYPE=Release"
          - name: "Mac"
            os: macos-12
            generator: "Xcode"
            definitions: ""
    
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3

      - name: Setup MSVC
        if: matrix.name == 'Win-VS'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Setup MSYS2
        if: matrix.name == 'Win-MinGW'
        uses: msys2/setup-msys2@v2
        with:
          msystem: 'mingw64'
          update: true
            git
            make
          pacboy: >-
            toolchain:p
            cmake:p
            ninja:p

      - name: Configure
        run: cmake -G "${{ matrix.generator }}" -S ./ -B build -DCMAKE_INSTALL_PREFIX=install -DNC_COMMON_BUILD_TESTS=ON ${{ matrix.definitions }}

      - name: Build
        run: cmake --build build --target install --config Release --parallel 2
      
      - name: Run Tests
        working-directory: ${{ github.workspace }}/build/test
        run: ctest -V --output-on-failure --output-junit TestResults.xml
      
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.name }}-TestResults
          path: build/test/TestResults.xml

  Publish-Test-Results:
    runs-on: ubuntu-latest
    needs: [Build]
    permissions:
      checks: write
      pull-requests: write
    if: always()

    steps:
    - name: Download Results
      uses: actions/download-artifact@v3
      with:
        path: artifacts

    - name: Publish Results
      uses: mikepenz/action-junit-report@v3
      if: always()
      with:
        report_paths: 'artifacts/**/*.xml'
